run:
  go: "1.20"

linters-settings:
  forbidigo:
    forbid:
      - 'log\.Print.*'
      - 'fmt\.Print.*'

  gofumpt:
    extra-rules: true

  goimports:
    local-prefixes: github.com/kylebrantley/seer

  nolintlint:
    require-explanation: true
    require-specific: true

linters:
  disable-all: true
  enable:
    - bidichk
    - errcheck
    - errname
    - forcetypeassert
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - godot
    - gofumpt
    - goimports
    - gosec
    - gosimple
    - ineffassign
    - makezero
    - misspell
    - nolintlint
    - nonamedreturns
    - prealloc
    - revive
    - staticcheck
    - tenv
    - thelper
    - typecheck
    - unused
    - usestdlibvars
    - wrapcheck
    - wsl
    - whitespace